"""empty message

Revision ID: 5b74f3924d2e
Revises: affea19884ed
Create Date: 2023-07-08 20:30:31.144905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b74f3924d2e'
down_revision = 'affea19884ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_memberships_status'), ['status'], unique=False)

    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_messages_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('live_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_chats_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    with op.batch_alter_table('live_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_chats_created_at'))

    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_messages_created_at'))

    with op.batch_alter_table('channel_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_memberships_status'))

    # ### end Alembic commands ###
