"""empty message

Revision ID: 8bf3f2bd06f4
Revises: 5b74f3924d2e
Create Date: 2023-07-08 20:43:49.410667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf3f2bd06f4'
down_revision = '5b74f3924d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index('ix_teams_name')
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.create_index('ix_teams_name', ['name'], unique=False)

    # ### end Alembic commands ###
